version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: poc
    environment:
      SA_PASSWORD: "387418Er****"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./Poc/SQL:/var/opt/mssql/backup
      - ./Poc/data:/var/opt/mssql/data